default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: <%= ENV["MYSQL_GC_USERNAME"] %>
  password: <%= ENV["MYSQL_GC_PASSWORD"] %>
  encoding: utf8

development:
  <<: *default
  database: g-commerce_dev

test:
  <<: *default
  database: g-commerce_test

production:
  <<: *default
  database: g-commerce_prod
